List<Map<String, dynamic>> emotionQuotes = [
  {
    "category": "Angry",
    "quotes": [
      "My existence is for myself; I do not exist to impress others.",
      "I am angry; it is a feeling that makes your tongue work faster than the brain.",
      "The best way to get someone’s attention is to stop giving them your attention.",
      "Life is short, do not waste it on me.",
      "You lose your importance in their life when you give lots of importance to them. .",
      "Quit talking to me if you do not like my attitude.",
      "You do not need to explain, I know who I am,",
      "I’ll leave you like a choice if you treat me like an option.",
      "My life, my attitude",
      "Maybe I am not perfect, but I am always me.",
      "Make sure that you are perfect if you are going to judge me.",
      "I’m not a WhatsApp status; I do not mind if you do not like me.",
      "Think before you talk; even when you are mad, the words you say can only be forgiven but not forgettable.",
      "Hey you! I found something under my shoes; oh, it’s your fucking attitude.",
      "You can copy my behavior, not my attitude.",
      "Hey, I am busy; feed your ego. .",
      "You need to control your temper if you want me to control my attitude.",
      "I do not usually lose my temper, but if I do, I am crazy.",
      "My anger is just the result of unsolved issues .",
      "You’re all dead to me. Everyone who played me lied to me and left me.",
      "You lost me for real once I stopped arguing with you.",
      "When someone ignores you, it doesn’t mean he hates you; it means you hurt him",
      "Please do not talk to me; I need an attitude adjustment. .",
      "Normal is boring; I am crazy.",
      "Love me, or hate me, but you can not change me.",
    ],
  },
  {
    "category": "Fear",
    "quotes": [
      "Do one thing every day that scares you. -Eleanor Roosevelt",
      "Each of us must confront our own fears, must come face to face with them.",
      "Everything you want is on the other side of fear. -Jack Canfield",
      "Extreme fear can neither fight nor fly. -William Shakespeare",
      "Failure  does not mean you are a failure; it just means you have not succeeded yet. -Robert H. Schuller",
      "Failure is a detour, not a dead-end street. -Zig Ziglar",
      "Fear has its use, but cowardice has none. -Gandhi",
      "Fear is only as deep as the mind allows. -Japanese Proverb",
      "Fear is the main source of superstition, and one of the main sources of cruelty. To conquer fear is the beginning of wisdom. -Bertrand Russell",
      "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering. -Yoda. Fears are nothing more than a state of mind. -Napoleon Hill",
      "Feel the fear and do it anyway. -Susan Jeffers. Have no fear of perfection. You will never reach it.  -Salvador Dali",
      "He who is not everyday conquering some fear has not learned the secret of life. -Ralph Waldo Emerson",
      "I failed my way to success. -Thomas Edison",
      "I have learned over the years that when one’s mind is made up, this diminishes fear; knowing what must be do note does away with fear. -Rosa Parks",
      "I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear. -Nelson Mandela",
      "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment. -Marcus Aurelius",
      "In skating over thin ice our safety is in our speed. -Ralph Waldo Emerson",
      "Inaction breeds doubt and fear. Action breeds confidence and courage. If you want to conquer fear, do not sit home and think about it. Go out and get busy. -Dale Carnegie",
      "It is hard to fail, but it is worse never to have tried to succeed. -Theodore Roosevelt",
      "Men are not afraid of things, but of how they view them. -Epictetus",
    ],
  },
  {
    "category": "Pain",
    "quotes": [
      "Pain is inevitable, suffering is optional.",
      "Time is not a cure for chronic pain, but it can be crucial for improvement. It takes time to change, to recover, and to make progress.",
      "Sometimes I think I shouldn’t feel the way I do. When I start thinking this way I tell myself that feelings are neither good nor bad—they simply are",
      "Sometimes things fall apart so that better things can fall together.",
      "I do not believe in pain management anymore, I believe in trying to cure persistent pain.",
      "Some people think that to be strong is to never feel pain. In reality, the strongest people are the ones who feel it, understand it, and accept it.",
      "When pain brings you down, do not be silly, do not close your eyes and cry, you just might be in the best position to see the sunshine.",
      "The longer you have pain, the better your spinal cord gets at producing danger messages to the brain, even if there is no danger in the tissue.",
      "There is a point to changes like these. I have to move on to other things, to other conceptions of myself. I play golf. I still work. And I can be pretty happy just walking the land.",
      "Healing severe or chronic pain, I believe, includes transforming our relationship to the pain, and, ultimately, it is about transforming our relationship to who we are and to life.",
      "I thought I was going to die [but] I ve gone from where I can not function, where  I just can not live like this  to  I ve got a bad headache. ",
      "Chronic pain is not all about the body, and it is not all about the brain—it is everything. Target everything. Take back your life.",
      "Pain is always accompanied by emotion and meaning so that each pain is unique to the individual",
      "I hope that people watching it that do struggle with chronic pain know that they are not alone",
      "do not fight your pain; you can not win. The paradox of recovery is that you have to surrender to win",
      "The body does not give up on us, so we can not give up on it. My goal is always to work with my body, not against it so that it can function efficiently",
      "And once the storm is over, you won t remember how you made it through, how you managed to survive.",
      "Since chronic pain frequently cannot be seen or measured, unlike acute pain, doctors, colleagues, friends, or family",
      "It is not about getting over things, it is about making room for them. It is about painting the picture with contrast",
      "It is been a long recovery... You can not mourn for how you used to feel... You have to come to terms with it.",
      "The strongest people are not those who show strength in front of us, but those who win battles we know nothing about.",
      "Our strength grows out of our weaknesses.",
      "You are not defeated when you lose. You are defeated when you quit.",
      "The journey of recovery from chronic disease is a long and winding road of small victories.",
      "Maybe I wasn t necessarily really good at knowing what that meant so it actually got to a point where it was life-or-death.",
      "Tough times never last, but tough people do.",
      "I ve always thought that if you work really hard at something, you can get it. But I was faced with the reality that this just wasn t happening",
      "There are times it just comes out of nowhere and really kicks me in the ass.",
      "You force yourself to get up. You force yourself to put one foot before the other, and God damn it",
    ],
  },
  {
    "category": "Confusion",
    "quotes": [
      "These confused quotes will inspire you to find direction when you’re feeling lost.",
      "While many things are uncertain in life, one sure thing is you can expect to be confused a lot of the time.",
      "Each of us gets confused by different things, but some of them we have in common.",
      "The most important thing is whether being confused bothers you or not.",
      "Some people thrive on being confused, because they feel it is the best way to learn and grow.",
      "Most of the time, you need to research and find more information about the topic that is making you confused.",
      "One way to do this is to talk to someone who is experienced and knowledgeable on the subject.",
      "As you read through these confusion quotes, you will gain insight into how to handle situations where you find yourself confused.",
      "do not forget to also check out our collection of quotes about hypocrisy for more insights.",
      "Check out our most popular quote article, a list of short inspirational quotes for daily inspiration.",
      "If you enjoy this collection, check out our inspirational quotes category page.",
      "The world has always been uncertain. This is the nature of the world.",
      "Man’s role is uncertain, undefined, and perhaps unnecessary.",
      "The thing about democracy, beloveds, is that it is not neat, orderly, or quiet",
      "True genius resides in the capacity for evaluation of uncertain, hazardous, and conflicting information.",
      "When a man’s knowledge is not in order, the more of it he has the greater will be his confusion.",
      "May the forces of evil become confused on the way to your house.",
      "The very essence of leadership is that you have to have vision. You can not blow an uncertain trumpet.",
      "Truth is ever to be found in simplicity, and not in the multiplicity and confusion of things.",
      "Truth emerges more readily from error than from confusion.",
      "I’m always looking, and I’m always asking questions.",
      "Seek first to understand, then to be understood.",
      "I hear and I forget. I see and I remember. I do and I understand",
      "If I look confused it is because I am thinking.",
      "I experience a period of frightening clarity in those moments when nature is so beautiful.",
      "Take advantage of every opportunity to practice your communication skills so that when important occasions arise, you will have the gift.",
      "The beauty is that through disappointment you can gain clarity, and with clarity comes conviction and true originality.",
      "Most people living in the world are confused about life.",
      "Things are always either black or white. The grey in between is only a confusion.",
    ],
  },
  {
    "category": "Boredom",
    "quotes": [
      "Boredom is the root of all evil – the despairing refusal to be oneself. – Soren Kierkegaard",
      "The two enemies of human happiness are pain and boredom. – Arthur Schopenhauer",
      "Boredom is just the reverse side of fascination: both depend on being outside rather than inside a situation, and one leads to the other. – Arthur Schopenhauer",
      "Boredom: The desire for desires. – Leo Tolstoy",
      "I’ve got a great ambition to die of exhaustion rather than boredom. – Thomas Carlyle",
      "To do the same thing over and over again is not only boredom: it is to be controlled by rather than to control what you do. – Heraclitus",
      "Your true traveler finds boredom rather agreeable than painful. It is the symbol of his liberty - his excessive freedom. He accepts his boredom, when it comes, not merely philosophically, but almost with pleasure. – Aldous Huxley",
      "Perhaps the world’s second worst crime is boredom. The first is being a bore. – Jean Baudrillard",
      "She refused to be bored chiefly because she wasn’t boring. – Zelda Fitzgerald, The Collected Writings",
      "There are no uninteresting things, only uninterested people. – G.K. Chesterton",
      "Is life not a thousand times too short for us to bore ourselves? – Friedrich Nietzsche",
      "The truth is that everyone is bored, and devotes himself to cultivating habits. – Albert Camus, The Plague",
      "I’m bored” is a useless thing to say. I mean, you live in a great, big, vast world that you’ve seen none percent of. Even the inside of your own mind is endless, it goes on forever, inwardly, do you understand? The fact that you’re alive is amazing, so you do not’t get to say ‘I’m bored.” – Louis C.K.",
      "Boredom is the conviction that you can not change…the shriek of unused capacities. – Saul Bellow, The Adventures of Augie March",
      "Millions long for immortality who do not know what to do with themselves on a rainy Sunday afternoon. – Susan Ertz",
      "He had been bored, that is all, bored like most people. Hence he had made himself out of whole cloth a life full of complications and drama. – Albert Camus, The Fall",
      "When people are bored, it is primarily with their own selves that they are bored. – Eric Hoffer",
      "Boredom is the fear of self. – Marie Josephine de Suin",
      "My despair is less despair than boredom and loneliness. – Anthony Swofford, Jarhead",
      "I am convinced that boredom is one of the greatest tortures. If I were to imagine Hell, it would be the place where you were continually bored. – Erich Fromm, The Dogma of Christ",
      "Boredom is the deadliest poison. – William F. Buckley, Jr., Milestones",
      "The cure for boredom is curiosity. There is no cure for curiosity. – Ellen Parr",
      "In order to live free and happily, you must sacrifice boredom. It is not always an easy sacrifice. – Richard Bach",
      "There’s no excuse to be bored. Sad, yes. Angry, yes. Depressed, yes, Crazy, yes. But there’s no excuse for boredom, ever. – Viggo Mortensen",
      "Unless a man has been taught what to do with success after getting it, the achievement of it must inevitably leave him a prey to boredom. – Bertrand Russell",
    ],
  },
  {
    "category": "Sadness",
    "quotes": [
      "You cannot protect yourself from sadness without protecting yourself from happiness.",
      "adness flies away on the wings of time.",
      "on't cry over someone who wouldn't cry over you.",
      "ny fool can be happy. It takes a man with real heart to make beauty out of the stuff that makes us weep.",
      "e must understand that sadness is an ocean, and sometimes we drown, while other days we are forced to swim.",
      "he word ‘happy’ would lose its meaning if it were not balanced by sadness.",
      "ears are words that need to be written.",
      "adness is but a wall between two gardens.",
      "ne must not let oneself be overwhelmed by sadness.",
      "Sadness is also a kind of defense.",
      "The walls we build around us to keep sadness out also keeps out the joy.",
      "here are moments when I wish I could roll back the clock and take all the sadness away, but I have a feeling that if I did, the joy would be gone as well. So, I take the memories as they come, accepting them all, letting them guide me whenever I can.",
      "We’re taught to be ashamed of confusion, anger, fear, and sadness, and to me, they’re of equal value to happiness, excitement, and inspiration.",
      "Experiencing sadness and anger can make you feel more creative, and by being creative you can get beyond your pain or negativity.",
      "Sad hurts but it's a healthy feeling. It is a necessary thing to feel.",
      "There are two types of people in the world: Those who prefer to be sad among others, and those who prefer to be sad alone.",
      "With some pain is fraught; Our sweetest songs are those that tell of saddest thought.",
      "It is sad not to love, but it is much sadder not to be able to love.",
      "Behind every sweet smile, there is a bitter sadness that no one can ever see and feel.",
      "Every man has his secret sorrows which the world knows not; and often times we call a man cold when he is only sad.",
      "Some days are just bad days, that’s all. You have to experience sadness to know happiness, and I remind myself that not every day is going to be a good day, that’s just the way it is!",
      "In deep sadness there is no place for sentimentality.",
      "Every human walks around with a certain kind of sadness. They may not wear it on their sleeves, but it’s there if you look deep.",
      "Better by far you should forget and smile than that you should remember and be sad.",
      "We never taste happiness in perfection, our most fortunate successes are mixed with sadness.",
    ],
  },
  {
    "category": "Surprise",
    "quotes": [
      "No one she knew had seen a can of peaches in years. She looked at the other one. It was just as amazing- ‘Creamed Corn,’ it said.",
      "You’d be surprised how many people violate this simple principle every day of their lives and try to fit square pegs into round holes, ignoring the clear reality that Things Are As They Are.",
      "One face, one voice, one habit, and two persons!",
      "If it be thus to dream, still let me sleep",
      "The air at Base Camp seemed thick and rich and voluptuously saturated with oxygen compared to the brutally thin atmosphere of the camps above.",
      "Without warning, the statue squirmed and bit the side of his thumb. Yelling in surprise, Seth dropped the figurine and the flashlight onto the carpeted floor.",
      "Surprises are foolish things. The pleasure is not enhanced, and the inconvenience is often considerable.",
      "Without warning, Hugo wrapped his arms around Isabelle’s neck and gave her a big hug. He could tell she was surprised.",
      "I recognize the desire to surprise your own life. ‘You must change your life,’ as the poet Rilke said",
      "The ending is always a surprise.",
      "Walsh hugs me, taking me by surprise. ‘I don’t know how,’ she mutters, ‘but I hope you become queen one day. Imagine what you could do then? The Red queen",
      "The edges of the drawings were yellowed and brittle, but they were all beautiful, and they were all by Georges Méliès",
      "I was amazed that what I needed to survive could be carried on my back. And, most surprising of all, that I could carry it.",
      "I am Abhorsen...” He looked at the baby again and added, almost with a note of surprise, “Father of Sabriel",
      "Leave it to me: I’m always top banana in the shock department.",
      "I just don’t like my world disturbed without some warning.",
      "The attackers had used one of the oldest and most potent weapons of warfare: surprise.",
      "Stories are as unique as the people who tell them, and the best stories are in which the ending is a surprise.",
      "Best friends can also be full of surprises.",
      "Really, though, what do I know about what another person is capable of? I still don’t have a clue what I’m capable of. I keep surprising even myself.",
      "One of the delights of the fair was never knowing who might turn up beside you.",
      "I noticed that my fear never changed, never delighted, never offered a surprise twist or an unexpected ending.",
      "If you make a deal with a fool, don’t be surprised when they act foolishly.",
    ],
  },
  {
    "category": "Horror",
    "quotes": [
      "Everybody is a book of blood; wherever we’re opened, we’re red.” — Clive Barker",
      "Where there is no imagination, there is no horror.” — Arthur Conan Doyle",
      "Would you like to see a magic trick? — The Grabber, The Black Phone",
      "Horror is like a serpent; always shedding its skin, always changing. And it will always come back.",
      "There is something at work in my soul which I do not understand.Frankenstein",
      "I’m scared to close my eyes, I’m scared to open them. We’re gonna die out here.” — Heather Donahue, The Blair Witch Project",
      "Is there someone inside you?” — Psychiatrist, The Exorcist",
      "I know of witches who whistle at different pitches, calling things that don’t have names.” — Helen Oyeyemi,White is for Witching",
      "This is all it takes for people to plunge into insanity: one night alone with themselves and what they fear the most.” — Thomas Olde Heuvelt, Hex",
      "They’re here.” — Carol Anne, Poltergeist",
      "Come, dear. It’ll be easier for you than it was for Jason.”  — Mrs. Voorhees, Friday the 13th",
      "I knew nothing but shadows and I thought them to be real.” -Oscar Wilde, The Picture of Dorian Gray",
      "Let’s talk, you and I. Let’s talk about fear.” — Stephen King, Night Shift",
      "Dementors are vicious creatures. They will not distinguish between the one they hunt and the one who gets in their way.” — Albus Dumbledore, Harry Potter and the Prisoner of Azkaban",
      "Evil thenceforth became my good.” — Mary Shelley, Frankenstein",
      "Evil has only the power that we give it.” — Ray Bradbury, Something Wicked This Way Comes",
      "When shall we meet again? In thunder, lightening, or in rain?” — First Witch, Macbeth",
      "I’m not gonna hurt ya. You didn’t let me finish my sentence. I said, ‘I’m not gonna hurt ya. I’m just going to bash your brains in!’” — Jack Torrance, The Shining",
      "I shall never forget the afternoon when first I stumbled upon the half-hidden house of the dead.” — H.P. Lovecraft, The Tomb",
      "Once upon a time, there was a girl and the girl had a shadow.” — Red, Us",
      "I don’t know who he is, but he’s burned, and he wears a weird hat and a red and green sweater, really dirty. And he uses these knives, like giant fingernails.” — Nancy Thompson, A Nightmare on Elm Street",
      "In this town, Michael Myers is a myth. He’s the Boogeyman. A ghost story to scare kids. But this Boogeyman is real. An evil like his never stops, it just grows older. Darker.” — Laurie Strode, Halloween (2018)",
    ],
  },

];
